---
- hosts: kubernetes_control
  become: true
  remote_user: na
  gather_facts: false
  roles:
    - control

- hosts: kubernetes_master
  become: true
  remote_user: na
  gather_facts: false
  roles:
    - master

- hosts: kubernetes_workers
  become: true
  remote_user: na
  gather_facts: false
  roles:
    - worker