---
- name: "copy tokens to masters"
  copy:
    src: "{{ item }}"
    dest: /tmp
    mode: u=rw,g=r,o=r
  with_items:
    - /tmp/k8s_token
    - /tmp/k8s_master_ca_hash
    - /tmp/k8s-cert-key

- name: "join cluster"
  shell: "kubeadm join --token $(cat /tmp/k8s_token) {{ master.load_balancer_ip }}:6443 --cri-socket=unix:///var/run/cri-dockerd.sock --discovery-token-ca-cert-hash sha256:$(cat /tmp/k8s_master_ca_hash) --control-plane --certificate-key $(cat /tmp/k8s-cert-key)"