---
control:
  kubeadm_extra_args: "--pod-network-cidr=10.244.0.0/16 --cri-socket=unix:///var/run/cri-dockerd.sock --skip-phases=addon/kube-proxy"
  kubeadm_use_load_balancer: "--upload-certs"
  load_balancer_ip: "{{groups['kubernetes_vip_load_balancer'][0]}}"
  load_balancer_port: 6443
