---
- name: disable swap
  shell: |
          sudo swapoff -a
          sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Download CRI-Dockerd
  command: wget https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.4/cri-dockerd_0.3.4.3-0.ubuntu-jammy_amd64.deb

- name: Install cri-dockerd
  command: dpkg -i /home/cleo/cri-dockerd_0.3.4.3-0.ubuntu-jammy_amd64.deb

- name: reload daemon 
  command: systemctl daemon-reload

- name: enable cri-docker.service
  command: systemctl enable cri-docker.service

- name: enable enable --now cri-docker.socket
  command: systemctl enable --now cri-docker.socket   